from . import medical_exam_type
from . import hr_employee
from . import hr_employee_base
from . import hr_employee_permit
from . import hr_contract_extended
from . import hr_permit_config
from . import hr_permit_alert
from . import hr_fiche_aptitude
from . import medical_exam_wizard
